Repository mikitachab/score-board, pull requests merged in 2020-11, with the labels that each got.

#29 github actions, golint
  .github/workflows/ci.yml
  .gitignore
  Makefile
  db/db.go
  db/models.go
  db/repository.go
  server/server.go
  templateloader/template_loader.go
Labels: DevOps

#30 add logging and recovery middleware
  server/middleware.go
  server/server.go
Labels: enhancement

#32 [partial] main page view
  db/repository.go
  server/card.go
  server/server.go
  template/index.html
Labels: feature

#31 Tests
  Makefile
  db/repository.go
  go.mod
  go.sum
  mocks/mock_repository.go
  server/server.go
  server/server_test.go
  templateloader/template_loader.go
Labels: DevOps, enhancement
